//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CercleCulturalEntities4 : DbContext
    {
        public CercleCulturalEntities4()
            : base("name=CercleCulturalEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Esdeveniment> Esdeveniment { get; set; }
        public virtual DbSet<Espai> Espai { get; set; }
        public virtual DbSet<Mensajes> Mensajes { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Seients> Seients { get; set; }
        public virtual DbSet<Usuari> Usuari { get; set; }
    }
}
