//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esdeveniment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esdeveniment()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string descripcio { get; set; }
        public System.DateTime dataInici { get; set; }
        public System.DateTime dataFi { get; set; }
        public int aforament { get; set; }
        public int espai_id { get; set; }
        public int usuari_id { get; set; }
        public string imatge { get; set; }
        public bool per_infants { get; set; }
    
        public virtual Espai Espai { get; set; }
        public virtual Usuari Usuari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
