//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espai()
        {
            this.Esdeveniment = new HashSet<Esdeveniment>();
            this.Reserva = new HashSet<Reserva>();
            this.Seients = new HashSet<Seients>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int capacitat { get; set; }
        public string ubicacio { get; set; }
        public decimal metres_quadrats { get; set; }
        public bool butaques_fixes { get; set; }
        public Nullable<int> num_files { get; set; }
        public Nullable<int> num_butaques_per_fila { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esdeveniment> Esdeveniment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seients> Seients { get; set; }
    }
}
