//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int id { get; set; }
        public int usuari_id { get; set; }
        public string nom_usuari { get; set; }
        public string missatge { get; set; }
        public System.DateTime dataEnviament { get; set; }
    
        public virtual Usuari Usuari { get; set; }
    }
}
