//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.Seients = new HashSet<Seients>();
        }
    
        public int id { get; set; }
        public int usuari_id { get; set; }
        public System.DateTime dataReserva { get; set; }
        public string estat { get; set; }
        public string tipus { get; set; }
        public Nullable<int> espai_id { get; set; }
        public Nullable<int> esdeveniment_id { get; set; }
        public Nullable<System.DateTime> dataInici { get; set; }
        public Nullable<System.DateTime> dataFi { get; set; }
        public Nullable<int> numPlaces { get; set; }
    
        public virtual Esdeveniment Esdeveniment { get; set; }
        public virtual Espai Espai { get; set; }
        public virtual Usuari Usuari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seients> Seients { get; set; }
    }
}
