//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationApiCercleCultural.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seients()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public int espai_id { get; set; }
        public bool numerat { get; set; }
        public string fila { get; set; }
        public string columna { get; set; }
        public string estat { get; set; }
    
        public virtual Espai Espai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
